//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreestyleTrainer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreestyleTrainer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap main_image_star_forming_region_carina_nircam_final_5mb {
            get {
                object obj = ResourceManager.GetObject("main_image_star-forming_region_carina_nircam_final-5mb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;words&quot;: [
        ///    &quot;Beautiful&quot;,
        ///    &quot;Incredible&quot;,
        ///    &quot;Impossible&quot;,
        ///    &quot;Wonderful&quot;,
        ///    &quot;Amazing&quot;,
        ///    &quot;Fantastic&quot;,
        ///    &quot;Unstoppable&quot;,
        ///    &quot;Unbreakable&quot;,
        ///    &quot;Miraculous&quot;,
        ///    &quot;Phenomenal&quot;,
        ///    &quot;Magnificent&quot;,
        ///    &quot;Inspirational&quot;,
        ///    &quot;Celebration&quot;,
        ///    &quot;Imagination&quot;,
        ///    &quot;Determination&quot;,
        ///    &quot;Conversation&quot;,
        ///    &quot;Motivation&quot;,
        ///    &quot;Electrifying&quot;,
        ///    &quot;Invincible&quot;,
        ///    &quot;Revolutionary&quot;,
        ///    &quot;Extraordinary&quot;,
        ///    &quot;Communication&quot;,
        ///    &quot;Fascination&quot;,
        ///    &quot;Collaboration&quot;,
        ///    &quot;Identificati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
